# ---- 登录账户 ----
# 天勤帐号
# 注册地址:https://www.shinnytech.com/
tq_username : sancho
tq_password : lxzlxzlxz
# 实盘账户
accounts:
  - 0:
    com : '' # 期货公司如：H海通期货
    account : ''
    password : ''
    tcp : '' # 可选交易服务器地址如：tcp://1.2.3.4:1234/
  # 多账户示例
  # - 1:
  #   com : 'H海通期货' 
  #   account : '123456'
  #   password : '123456'
  #   tcp : 'tcp://1.2.3.4:1234/' 
# 回测时间区间
start_dt : [2021,01,01]
end_dt : [2022,01,01]
# 模拟资金
balance : 9999999

# ---- 订阅合约 ----
# 实时数据(合约代码)
quotes:
  - KQ.m@DCE.a
  - KQ.m@DCE.b
# K线数据(合约代码 : [数据周期/秒,序列长度])
klines:
  KQ.m@DCE.j:
    - 20
    - 200
  KQ.m@DCE.jd : 
    - 20
    - 200
# Tick数据(合约代码 : 序列长度)
ticks:
  KQ.m@DCE.i : 200
  KQ.m@DCE.l : 200

# ---- 交易设置 ----
price: 'ACTIVE' # 下单方式,ACTIVE=对价下单,PASSIVE=排队价下单
offset_priority: '今昨,开' # 开平仓顺序，昨=平昨仓，今=平今仓，开=开仓，逗号=等待之前操作完成
min_volume: None # 大单拆分模式下每笔最小下单的手数
max_volume: None # 大单拆分模式下每笔最大下单的手数


